export const ThirstItemEffectsByTypeId = Object.freeze({
  "minecraft:potion": { thirstDelta: 0.5, effect: { id: "poison", seconds: 6, chancePercent: 60 } },
  "addon:water_bottle": { thirstDelta: 6 },
  "minecraft:milk_bucket": { thirstDelta: 15 },

  "minecraft:apple": { thirstDelta: 1.2 },
  "minecraft:baked_potato": { thirstDelta: -1 },
  "minecraft:beetroot": { thirstDelta: 0.7 },
  "minecraft:beetroot_soup": { thirstDelta: 2 },
  "minecraft:bread": { thirstDelta: -1 },
  "minecraft:cake": { thirstDelta: -1 },
  "minecraft:carrot": { thirstDelta: 0.7 },
  "minecraft:chorus_fruit": { thirstDelta: 0.7 },
  "minecraft:cooked_chicken": { thirstDelta: -2 },
  "minecraft:cooked_cod": { thirstDelta: -1.6 },
  "minecraft:cooked_mutton": { thirstDelta: -2.5 },
  "minecraft:cooked_porkchop": { thirstDelta: -3 },
  "minecraft:cooked_rabbit": { thirstDelta: -1.5 },
  "minecraft:cooked_salmon": { thirstDelta: -1.6 },
  "minecraft:cookie": { thirstDelta: -0.3 },
  "minecraft:dried_kelp": { thirstDelta: -0.3 },
  "minecraft:enchanted_golden_apple": { thirstDelta: 3 },
  "minecraft:golden_apple": { thirstDelta: 3 },
  "minecraft:glow_berries": { thirstDelta: 1 },
  "minecraft:golden_carrot": { thirstDelta: 1.5 },
  "minecraft:honey_bottle": { thirstDelta: -0.7 },
  "minecraft:melon_slice": { thirstDelta: -10 },
  "minecraft:mushroom_stew": { thirstDelta: 2 },
  "minecraft:poisonous_potato": { thirstDelta: 0.5 },
  "minecraft:potato": { thirstDelta: 0.5 },
  "minecraft:pufferfish": { thirstDelta: -0.5 },
  "minecraft:pumpkin_pie": { thirstDelta: -2 },
  "minecraft:rabbit_stew": { thirstDelta: 2 },
  "minecraft:beef": { thirstDelta: -1 },
  "minecraft:chicken": { thirstDelta: -1 },
  "minecraft:cod": { thirstDelta: -0.5 },
  "minecraft:mutton": { thirstDelta: -1 },
  "minecraft:porkchop": { thirstDelta: -1 },
  "minecraft:rabbit": { thirstDelta: -0.5 },
  "minecraft:salmon": { thirstDelta: -0.5 },
  "minecraft:rotten_flesh": { thirstDelta: -3 },
  "minecraft:spider_eye": { thirstDelta: -3 },
  "minecraft:cooked_beef": { thirstDelta: -2 },
  "minecraft:suspicious_stew": { thirstDelta: 2 },
  "minecraft:sweet_berries": { thirstDelta: 1 },
  "minecraft:tropical_fish": { thirstDelta: -0.5 },

  "addon:dunlin_donuts": { thirstDelta: -3 },
  "addon:kfc": { thirstDelta: -3 },
  "addon:m1": { thirstDelta: 2 },
  "addon:m2": { thirstDelta: 2 },
  "addon:m3": { thirstDelta: 2 },
  "addon:McDonald": { thirstDelta: -3 },
  "addon:su1": { thirstDelta: -3 },
  "addon:su2": { thirstDelta: -3 },
  "addon:the_coffee_bean": { thirstDelta: 3 },
  "addon:cooked_axolotl_bucket": { thirstDelta: 4 },
  "addon:cooked_axolotl_bucket_2": { thirstDelta: 4 },
  "addon:cooked_axolotl_bucket_3": { thirstDelta: 8 },
  "addon:co": { thirstDelta: 4 },
  "addon:sp_1": { thirstDelta: 4 },
  "addon:sp_2": { thirstDelta: 4 },
  "addon:sp_3": { thirstDelta: 4 },
  "addon:sp_4": { thirstDelta: 4 },
});

export const DrinkableEntityTypeIds = Object.freeze(["minecraft:cow", "minecraft:mooshroom"]);
export const DrinkableBlockTypeIds = Object.freeze(["minecraft:water", "minecraft:flowing_water"]);
