import { GameMode } from "@minecraft/server";

export const config = Object.freeze({
  saveKey: "waterLevel",
  cowTimerKey: "cowTime",
  full: 21,
  empty: 0,
  hurtTime: 6,
  showTime: 20,
  loopTime: 20,
  cowWait: 7,
  healPrice: 0.1,
  badModes: [GameMode.Creative, GameMode.Spectator],
});

export const rates = Object.freeze({
  drop: { easy: 0.00526, normal: 0.00625, hard: 0.00714 },
  cost: { run: 1.76, jump: 0.2, dry: 0.1 },
});

const colors = {
  pink: "§d",
  darkPink: "§m",
  cyan: "§z",
  teal: "§t",
  blue: "§b",
  reset: "§r",
  white: "§f",
};

export const barName = `${colors.pink}${colors.darkPink}${colors.cyan}${colors.teal}${colors.blue}${colors.reset}${colors.reset}${colors.white}`;

export const menu = Object.freeze({
  "minecraft:potion": { add: 0.5, magic: { id: "poison", time: 6, chance: 60 } },
  "addon:water_bottle": { add: 6 },
  "minecraft:milk_bucket": { add: 15 },
  "minecraft:apple": { add: 1.2 },
  "minecraft:baked_potato": { add: -1 },
  "minecraft:beetroot": { add: 0.7 },
  "minecraft:beetroot_soup": { add: 2 },
  "minecraft:bread": { add: -1 },
  "minecraft:cake": { add: -1 },
  "minecraft:carrot": { add: 0.7 },
  "minecraft:chorus_fruit": { add: 0.7 },
  "minecraft:cooked_chicken": { add: -2 },
  "minecraft:cooked_cod": { add: -1.6 },
  "minecraft:cooked_mutton": { add: -2.5 },
  "minecraft:cooked_porkchop": { add: -3 },
  "minecraft:cooked_rabbit": { add: -1.5 },
  "minecraft:cooked_salmon": { add: -1.6 },
  "minecraft:cookie": { add: -0.3 },
  "minecraft:dried_kelp": { add: -0.3 },
  "minecraft:enchanted_golden_apple": { add: 3 },
  "minecraft:golden_apple": { add: 3 },
  "minecraft:glow_berries": { add: 1 },
  "minecraft:golden_carrot": { add: 1.5 },
  "minecraft:honey_bottle": { add: -0.7 },
  "minecraft:melon_slice": { add: -10 },
  "minecraft:mushroom_stew": { add: 2 },
  "minecraft:poisonous_potato": { add: 0.5 },
  "minecraft:potato": { add: 0.5 },
  "minecraft:pufferfish": { add: -0.5 },
  "minecraft:pumpkin_pie": { add: -2 },
  "minecraft:rabbit_stew": { add: 2 },
  "minecraft:beef": { add: -1 },
  "minecraft:chicken": { add: -1 },
  "minecraft:cod": { add: -0.5 },
  "minecraft:mutton": { add: -1 },
  "minecraft:porkchop": { add: -1 },
  "minecraft:rabbit": { add: -0.5 },
  "minecraft:salmon": { add: -0.5 },
  "minecraft:rotten_flesh": { add: -3 },
  "minecraft:spider_eye": { add: -3 },
  "minecraft:cooked_beef": { add: -2 },
  "minecraft:suspicious_stew": { add: 2 },
  "minecraft:sweet_berries": { add: 1 },
  "minecraft:tropical_fish": { add: -0.5 },
  "addon:dunlin_donuts": { add: -3 },
  "addon:kfc": { add: -3 },
  "addon:m1": { add: 2 },
  "addon:m2": { add: 2 },
  "addon:m3": { add: 2 },
  "addon:McDonald": { add: -3 },
  "addon:su1": { add: -3 },
  "addon:su2": { add: -3 },
  "addon:the_coffee_bean": { add: 3 },
  "addon:cooked_axolotl_bucket": { add: 4 },
  "addon:cooked_axolotl_bucket_2": { add: 4 },
  "addon:cooked_axolotl_bucket_3": { add: 8 },
  "addon:co": { add: 4 },
  "addon:sp_1": { add: 4 },
  "addon:sp_2": { add: 4 },
  "addon:sp_3": { add: 4 },
  "addon:sp_4": { add: 4 },
});

export const lists = Object.freeze({
  cows: ["minecraft:cow", "minecraft:mooshroom"],
  waters: ["minecraft:water", "minecraft:flowing_water"],
});
