import { system } from "@minecraft/server";

function getString() {
  const utcNow = Date.now();
  const offsetMs = 7 * 60 * 60 * 1000;
  const thaiTime = new Date(utcNow + offsetMs);

  return thaiTime.toLocaleString("th-TH", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
}

const startTime = getString();
const tick = typeof system.currentTick === "number" ? system.currentTick : 0;
const BuildVer = `25.11.2025`;
const PatchVer = `v1.0`;
const text = `

                                .
                                  ...
                                  ....
                                    ....
                              ..   .....   .............
                              ...... ......................
                            ......  ............       .....
                          .   .....  .........          .....
                        ....        .........          ......
                        .          ........          .......
                        .         .........       ..........
                        .....    ...........     ...........
                      .....    ............    ..........
                        .. . ................   .........
              ....     .....................   .......
                  ...................  .......
                    ............       .......
                                        ......
                              ...        .......
                            ....         ......
                              .....       .......
                              ......     .......
                                .......   .......
                                ...............
                                    ...........
                                        ....

 .|'''.|  '||                           '||   ||    .               .|'''.|  '||    ||' '||''|.
 ||..  '   ||    ....    ....  ... ...   ||  ...  .||.    ....      ||..  '   |||  |||   ||   ||
  ''|||.   ||  .|...|| .|...||  ||'  ||  ||   ||   ||   .|...||      ''|||.   |'|..'||   ||...|'
.     '||  ||  ||      ||       ||    |  ||   ||   ||   ||         .     '||  | '|' ||   ||
|'....|'  .||.  '|...'  '|...'  ||...'  .||. .||.  '|.'  '|...'    |'....|'  .|. | .||. .||.
                                ||
                               ''''

----------------------------------------------------------------------
  Sleeplite SMP Server Pack * 2025 SolightzZ | All Rights Reserved
----------------------------------------------------------------------
  Game:         Minecraft Bedrock Edition | Version: 1.21.124
  Modules:      server, server-ui, server-admin
  Build:        ${BuildVer}  | Patch: ${PatchVer}
  Runtime:      Boot ${startTime} | Tick: ${tick} | Zone: THA (UTC+7)
  Server Type:  Minecraft Server (Vanilla)
  License:      Internal / MIT
  Developer:    SolightzZ
  Docs:         https://github.com/SolightzZ/SleepliteSMP
  Support:      https://discord.gg/gtqfbmvTJK
  Status:       Scripts loaded successfully!
----------------------------------------------------------------------
  `;

console.warn(text);
