export const DEFAULT_ICON = "textures/ui/sidebar_icons/character_creator";
export const STOP_ANIMATION = "animation.creaking.sway";

export const nss = [
  {
    label: "Buggie dance",
    animation: "buggie_dance",
    icon: "textures/emotes/buggie_dance",
  },
  {
    label: "Cute dance",
    animation: "cute_dance",
    icon: "textures/emotes/cute_dance",
  },
  {
    label: "Dabdance",
    animation: "dab_dance",
    icon: "textures/emotes/dab_dance",
  },
  {
    label: "Floss dance",
    animation: "floss_dance",
    icon: "textures/emotes/floss_dance",
  },
  { label: "Griddy", animation: "griddy", icon: "textures/emotes/griddy" },
  {
    label: "hakari_dance",
    animation: "hakari_dance",
    icon: "textures/emotes/hakari_dance",
  },
  {
    label: "Jojo pose",
    animation: "jojo_pose",
    icon: "textures/emotes/jojo_pose",
  },
  {
    label: "Kazoch kick",
    animation: "kazoch_kick",
    icon: "textures/emotes/kazoch_kick",
  },
  { label: "Laugh", animation: "laugh", icon: "textures/emotes/laugh" },
  { label: "Nop", animation: "nop", icon: "textures/emotes/nop" },
  {
    label: "Club penguin",
    animation: "club_penguin",
    icon: "textures/emotes/club_penguin",
  },
  {
    label: "Doodle dance",
    animation: "doodle_dance",
    icon: "textures/emotes/doodle_dance",
  },
  {
    label: "Snow angel",
    animation: "snow_angel",
    icon: "textures/emotes/snow_angel",
  },
  {
    label: "Rat dance",
    animation: "rat_dance",
    icon: "textures/emotes/rat_dance",
  },
  { label: "Sad", animation: "sad", icon: "textures/emotes/sad" },
  { label: "A5", animation: "a5", icon: "textures/emotes/a5" },
  { label: "Cry", animation: "cry", icon: "textures/emotes/cry" },
  {
    label: "Foldedarmspose",
    animation: "foldedarmspose",
    icon: "textures/emotes/foldedarmspose",
  },
  {
    label: "Headspin",
    animation: "headspin",
    icon: "textures/emotes/headspin",
  },
  {
    label: "Just dance",
    animation: "justdance",
    icon: "textures/emotes/justdance",
  },
  { label: "Oddloop", animation: "oddloop", icon: "textures/emotes/oddloop" },
  { label: "Rat2", animation: "rat2", icon: "textures/emotes/rat2" },
  {
    label: "Rollinghead",
    animation: "rollinghead",
    icon: "textures/emotes/rollinghead",
  },
  { label: "Shuba", animation: "shuba", icon: "textures/emotes/shuba" },
  {
    label: "Sitinbeach",
    animation: "sitinbeach",
    icon: "textures/emotes/sitinbeach",
  },
  { label: "Smile2", animation: "smile2", icon: "textures/emotes/smile2" },
  {
    label: "Leaningonthefence",
    animation: "leaningonthefence",
    icon: "textures/emotes/leaningonthefence",
  },
  {
    label: "Standupstraight",
    animation: "standupstraight",
    icon: "textures/emotes/standupstraight",
  },
  {
    label: "Lookatthewatch",
    animation: "lookatthewatch",
    icon: "textures/emotes/lookatthewatch",
  },
  { label: "Sitback", animation: "sitback", icon: "textures/emotes/sitback" },
  {
    label: "Headphone",
    animation: "headphone",
    icon: "textures/emotes/headphone",
  },
  {
    label: "Leaningagainstthewall",
    animation: "leaningagainstthewall",
    icon: "textures/emotes/leaningagainstthewall",
  },
  { label: "Besmall", animation: "besmall", icon: "textures/emotes/besmall" },
  { label: "Mockery", animation: "mockery", icon: "textures/emotes/mockery" },
  {
    label: "Littledance",
    animation: "littledance",
    icon: "textures/emotes/littledance",
  },
  { label: "Patpat1", animation: "patpat1", icon: "textures/emotes/patpat1" },
  { label: "Patpat2", animation: "patpat2", icon: "textures/emotes/patpat2" },
  { label: "Sl2", animation: "sl2", icon: "textures/emotes/sl2" },
  {
    label: "Spinswordd",
    animation: "spinswordd",
    icon: "textures/emotes/spinswordd",
  },
  { label: "St7", animation: "st7", icon: "textures/emotes/st7" },
  { label: "Flower", animation: "flower", icon: "textures/emotes/flower" },
  { label: "Flower2", animation: "flower2", icon: "textures/emotes/flower2" },
  { label: "Dnc10", animation: "dnc10", icon: "textures/emotes/dnc10" },
  { label: "Dnc11", animation: "dnc11", icon: "textures/emotes/dnc11" },
  { label: "St8", animation: "st8", icon: "textures/emotes/st8" },
  { label: "Wave", animation: "wave", icon: "textures/emotes/wave" },
];

export const nsx = [
  {
    label: "Floating",
    animation: "floating",
    icon: "textures/emotes/floating",
  },
  { label: "St9", animation: "st9", icon: "textures/emotes/st9" },
  { label: "St10", animation: "st10", icon: "textures/emotes/st10" },
  { label: "Dnc12", animation: "dnc12", icon: "textures/emotes/dnc12" },
  { label: "Stand9", animation: "stand9", icon: "textures/emotes/stand9" },
  { label: "Kewer", animation: "kewer", icon: "textures/emotes/kewer" },
  {
    label: "Ratdancere",
    animation: "ratdancere",
    icon: "textures/emotes/ratdancere",
  },
  { label: "Stand10", animation: "stand10", icon: "textures/emotes/stand10" },
  {
    label: "Superman",
    animation: "superman",
    icon: "textures/emotes/superman",
  },
  {
    label: "Leftright",
    animation: "leftright",
    icon: "textures/emotes/leftright",
  },
  {
    label: "Patfrontandback",
    animation: "patfrontandback",
    icon: "textures/emotes/patfrontandback",
  },
  {
    label: "Sitonthefloor",
    animation: "sitonthefloor",
    icon: "textures/emotes/sitonthefloor",
  },
  {
    label: "Onthefloor",
    animation: "onthefloor",
    icon: "textures/emotes/onthefloor",
  },
  {
    label: "Justdanceremake",
    animation: "justdanceremake",
    icon: "textures/emotes/justdanceremake",
  },
  { label: "Pushup", animation: "pushup", icon: "textures/emotes/pushup" },
  {
    label: "Sitsword",
    animation: "sitsword",
    icon: "textures/emotes/sitsword",
  },
  {
    label: "Sitsword2",
    animation: "sitsword2",
    icon: "textures/emotes/sitsword2",
  },
  {
    label: "Sleepsword",
    animation: "sleepsword",
    icon: "textures/emotes/sleepsword",
  },
  {
    label: "Sitsmoke",
    animation: "sitsmoke",
    icon: "textures/emotes/sitsmoke",
  },
  { label: "Smoke", animation: "smoke", icon: "textures/emotes/smoke" },
  { label: "Summon", animation: "summon", icon: "textures/emotes/summon" },
  {
    label: "Sitinbeach.2",
    animation: "sitinbeach.2",
    icon: "textures/emotes/sitinbeach.2",
  },
  {
    label: "Leantree",
    animation: "leantree",
    icon: "textures/emotes/leantree",
  },
  {
    label: "Leantree.2",
    animation: "leantree.2",
    icon: "textures/emotes/leantree.2",
  },
  { label: "Snow", animation: "snow", icon: "textures/emotes/snow" },
  { label: "Sit333", animation: "sit333", icon: "textures/emotes/sit333" },
  { label: "Sleep3", animation: "sleep3", icon: "textures/emotes/sleep3" },
  { label: "Sit555", animation: "sit555", icon: "textures/emotes/sit555" },
  {
    label: "Coverface",
    animation: "coverface",
    icon: "textures/emotes/coverface",
  },
  { label: "Tposess", animation: "tposess", icon: "textures/emotes/tposess" },
  { label: "Hskt1", animation: "hskt1", icon: "textures/emotes/hskt1" },
  {
    label: "Napwyou.2",
    animation: "napwyou.2",
    icon: "textures/emotes/napwyou.2",
  },
  { label: "Meme1", animation: "meme1", icon: "textures/emotes/meme1" },
  { label: "Napwyou", animation: "napwyou", icon: "textures/emotes/napwyou" },
  { label: "Hskt2", animation: "hskt2", icon: "textures/emotes/hskt2" },
  { label: "Sword1", animation: "sword1", icon: "textures/emotes/sword1" },
  { label: "Small", animation: "small", icon: "textures/emotes/small" },
  { label: "Gojo", animation: "gojo", icon: "textures/emotes/gojo" },
  { label: "Chill", animation: "chill", icon: "textures/emotes/chill" },
  {
    label: "Sitwyou2",
    animation: "sitwyou2",
    icon: "textures/emotes/sitwyou2",
  },
  { label: "Sitwyou", animation: "sitwyou", icon: "textures/emotes/sitwyou" },
  {
    label: "Relaxsleep",
    animation: "relaxsleep",
    icon: "textures/emotes/relaxsleep",
  },
];

export const SS = [
  { label: "Twerking", animation: "perreo", icon: "textures/emotes/perreo" },
  {
    label: "Helicopter",
    animation: "helicopter",
    icon: "textures/emotes/helicopter",
  },
  {
    label: "Take the T",
    animation: "baile_25",
    icon: "textures/emotes/baile_25",
  },
  {
    label: "Take the L",
    animation: "baile_18",
    icon: "textures/emotes/baile_18",
  },
  { label: "Llorar", animation: "llorar", icon: "textures/emotes/llorar" },
  {
    label: "Aquiestoy",
    animation: "aquiestoy",
    icon: "textures/emotes/aquiestoy",
  },
  { label: "Arigato", animation: "arigato", icon: "textures/emotes/arigato" },
  { label: "Floss", animation: "baile", icon: "textures/emotes/baile" },
  {
    label: "Desperate",
    animation: "baile_21",
    icon: "textures/emotes/baile_21",
  },
  {
    label: "Best Mates",
    animation: "baile_19",
    icon: "textures/emotes/baile_19",
  },
  { label: "Dab", animation: "dab", icon: "textures/emotes/dab" },
  {
    label: "Flip",
    animation: "flip_atras",
    icon: "textures/emotes/flip_atras",
  },
  { label: "Naca", animation: "naca", icon: "textures/emotes/naca" },
  { label: "Risa", animation: "risa", icon: "textures/emotes/risa" },
  { label: "T Pose", animation: "t-pose", icon: "textures/emotes/t-pose" },
  {
    label: "Zero Two",
    animation: "sneaking_1",
    icon: "textures/emotes/sneaking_1",
  },
];

export const GG = [
  { label: "ชี้ไปทางขวา", animation: "so14", icon: "textures/emotes/so14" },
  { label: "ไม่ได้เลย", animation: "so15", icon: "textures/emotes/so15" },
  { label: "ชิลล์", animation: "so13", icon: "textures/emotes/so13" },
  { label: "เขินอาย", animation: "so8", icon: "textures/emotes/so8" },
  { label: "แอ็ค", animation: "so1", icon: "textures/emotes/so1" },
  { label: "นั่งชิลล์", animation: "so3", icon: "textures/emotes/so3" },
  { label: "หมุนๆ", animation: "so5", icon: "textures/emotes/so5" },
  { label: "มายัง", animation: "so7", icon: "textures/emotes/so7" },
  { label: "มาแล้ว", animation: "so9", icon: "textures/emotes/so9" },
  { label: "ชี้ไปข้างบน", animation: "so10", icon: "textures/emotes/so10" },
  { label: "นั่งเศร้า", animation: "so11", icon: "textures/emotes/so11" },
  { label: "นอนกลางวัน", animation: "so17", icon: "textures/emotes/so17" },
  { label: "ปวดขาโว้ย", animation: "so18", icon: "textures/emotes/so18" },
  { label: "นั่งเล่น", animation: "so19", icon: "textures/emotes/so19" },
  { label: "Moon Walk", animation: "so16", icon: "textures/emotes/so16" },
  { label: "Size large", animation: "big", icon: "textures/emotes/so2" },
  { label: "Size small", animation: "so4", icon: "textures/emotes/so4" },
  { label: "Size very small", animation: "so6", icon: "textures/emotes/so6" },
];

export const PM = [
  { label: "ชี้ไปทางซ้าย", animation: "play8", icon: "textures/emotes/play8" },
  {
    label: "ท่าเตรียมต่อสู้",
    animation: "play10",
    icon: "textures/emotes/play10",
  },
  { label: "เรียบร้อย", animation: "play13", icon: "textures/emotes/play13" },
  { label: "ขอส่วนบุญ", animation: "play12", icon: "textures/emotes/play12" },
  { label: "นอนราบ", animation: "play11", icon: "textures/emotes/play11" },
  { label: "นั่งเล่น", animation: "play17", icon: "textures/emotes/play17" },
  { label: "นั่งพัก", animation: "play2", icon: "textures/emotes/play2" },
  {
    label: "นั่งแอ็คซ้าย",
    animation: "play19",
    icon: "textures/emotes/play19",
  },
  { label: "พับเพียบ", animation: "play4", icon: "textures/emotes/play4" },
  { label: "นั่งแอ็คขวา", animation: "play5", icon: "textures/emotes/play5" },
  { label: "จับมือซ้าย", animation: "play6", icon: "textures/emotes/play6" },
  { label: "จับมือขวา", animation: "play7", icon: "textures/emotes/play7" },
  { label: "เอนตัว", animation: "play1", icon: "textures/emotes/play1" },
  { label: "เอียง", animation: "play9", icon: "textures/emotes/play9" },
  { label: "ยืนแอ็ค", animation: "play3", icon: "textures/emotes/play3" },
  { label: "นอนชิลล์", animation: "play14", icon: "textures/emotes/play14" },
  { label: "พิงอยู่", animation: "play15", icon: "textures/emotes/play15" },
  { label: "ทำมาเพื่อ", animation: "play16", icon: "textures/emotes/play16" },
  { label: "พิงเก้าอี้", animation: "play18", icon: "textures/emotes/play18" },
];
