import { CONFIG } from "./constants";

export const EMOTE_DB = [
  {
    id: "dexten",
    type: "CATEGORY",
    label: "Emote Dexten",
    title: "Emote Dexten List",
    icon: "textures/emotes/icon_main_Dexten",
    data: [
      { label: "Buggie dance", anim: "buggie_dance", icon: "textures/emotes/buggie_dance" },
      { label: "Cute dance", anim: "cute_dance", icon: "textures/emotes/cute_dance" },
      { label: "Dabdance", anim: "dab_dance", icon: "textures/emotes/dab_dance" },
      { label: "Floss dance", anim: "floss_dance", icon: "textures/emotes/floss_dance" },
      { label: "Griddy", anim: "griddy", icon: "textures/emotes/griddy" },
      { label: "hakari_dance", anim: "hakari_dance", icon: "textures/emotes/hakari_dance" },
      { label: "Jojo pose", anim: "jojo_pose", icon: "textures/emotes/jojo_pose" },
      { label: "Kazoch kick", anim: "kazoch_kick", icon: "textures/emotes/kazoch_kick" },
      { label: "Laugh", anim: "laugh", icon: "textures/emotes/laugh" },
      { label: "Nop", anim: "nop", icon: "textures/emotes/nop" },
      { label: "Club penguin", anim: "club_penguin", icon: "textures/emotes/club_penguin" },
      { label: "Doodle dance", anim: "doodle_dance", icon: "textures/emotes/doodle_dance" },
      { label: "Snow angel", anim: "snow_angel", icon: "textures/emotes/snow_angel" },
      { label: "Rat dance", anim: "rat_dance", icon: "textures/emotes/rat_dance" },
      { label: "Sad", anim: "sad", icon: "textures/emotes/sad" },
      { label: "A5", anim: "a5", icon: "textures/emotes/a5" },
      { label: "Cry", anim: "cry", icon: "textures/emotes/cry" },
      { label: "Foldedarmspose", anim: "foldedarmspose", icon: "textures/emotes/foldedarmspose" },
      { label: "Headspin", anim: "headspin", icon: "textures/emotes/headspin" },
      { label: "Just dance", anim: "justdance", icon: "textures/emotes/justdance" },
      { label: "Oddloop", anim: "oddloop", icon: "textures/emotes/oddloop" },
      { label: "Rat2", anim: "rat2", icon: "textures/emotes/rat2" },
      { label: "Rollinghead", anim: "rollinghead", icon: "textures/emotes/rollinghead" },
      { label: "Shuba", anim: "shuba", icon: "textures/emotes/shuba" },
      { label: "Sitinbeach", anim: "sitinbeach", icon: "textures/emotes/sitinbeach" },
      { label: "Smile2", anim: "smile2", icon: "textures/emotes/smile2" },
      { label: "Leaningonthefence", anim: "leaningonthefence", icon: "textures/emotes/leaningonthefence" },
      { label: "Standupstraight", anim: "standupstraight", icon: "textures/emotes/standupstraight" },
      { label: "Lookatthewatch", anim: "lookatthewatch", icon: "textures/emotes/lookatthewatch" },
      { label: "Sitback", anim: "sitback", icon: "textures/emotes/sitback" },
      { label: "Headphone", anim: "headphone", icon: "textures/emotes/headphone" },
      { label: "Leaningagainstthewall", anim: "leaningagainstthewall", icon: "textures/emotes/leaningagainstthewall" },
      { label: "Besmall", anim: "besmall", icon: "textures/emotes/besmall" },
      { label: "Mockery", anim: "mockery", icon: "textures/emotes/mockery" },
      { label: "Littledance", anim: "littledance", icon: "textures/emotes/littledance" },
      { label: "Patpat1", anim: "patpat1", icon: "textures/emotes/patpat1" },
      { label: "Patpat2", anim: "patpat2", icon: "textures/emotes/patpat2" },
      { label: "Sl2", anim: "sl2", icon: "textures/emotes/sl2" },
      { label: "Spinswordd", anim: "spinswordd", icon: "textures/emotes/spinswordd" },
      { label: "St7", anim: "st7", icon: "textures/emotes/st7" },
      { label: "Flower", anim: "flower", icon: "textures/emotes/flower" },
      { label: "Flower2", anim: "flower2", icon: "textures/emotes/flower2" },
      { label: "Dnc10", anim: "dnc10", icon: "textures/emotes/dnc10" },
      { label: "Dnc11", anim: "dnc11", icon: "textures/emotes/dnc11" },
      { label: "St8", anim: "st8", icon: "textures/emotes/st8" },
      { label: "Wave", anim: "wave", icon: "textures/emotes/wave" },
    ],
  },
  {
    id: "euforia",
    type: "CATEGORY",
    label: "Emote Euforia",
    title: "Emote Euforia List",
    icon: "textures/emotes/icon_main_Euforia",
    data: [
      { label: "Floating", anim: "floating", icon: "textures/emotes/floating" },
      { label: "St9", anim: "st9", icon: "textures/emotes/st9" },
      { label: "St10", anim: "st10", icon: "textures/emotes/st10" },
      { label: "Dnc12", anim: "dnc12", icon: "textures/emotes/dnc12" },
      { label: "Stand9", anim: "stand9", icon: "textures/emotes/stand9" },
      { label: "Kewer", anim: "kewer", icon: "textures/emotes/kewer" },
      { label: "Ratdancere", anim: "ratdancere", icon: "textures/emotes/ratdancere" },
      { label: "Stand10", anim: "stand10", icon: "textures/emotes/stand10" },
      { label: "Superman", anim: "superman", icon: "textures/emotes/superman" },
      { label: "Leftright", anim: "leftright", icon: "textures/emotes/leftright" },
      { label: "Patfrontandback", anim: "patfrontandback", icon: "textures/emotes/patfrontandback" },
      { label: "Sitonthefloor", anim: "sitonthefloor", icon: "textures/emotes/sitonthefloor" },
      { label: "Onthefloor", anim: "onthefloor", icon: "textures/emotes/onthefloor" },
      { label: "Justdanceremake", anim: "justdanceremake", icon: "textures/emotes/justdanceremake" },
      { label: "Pushup", anim: "pushup", icon: "textures/emotes/pushup" },
      { label: "Sitsword", anim: "sitsword", icon: "textures/emotes/sitsword" },
      { label: "Sitsword2", anim: "sitsword2", icon: "textures/emotes/sitsword2" },
      { label: "Sleepsword", anim: "sleepsword", icon: "textures/emotes/sleepsword" },
      { label: "Sitsmoke", anim: "sitsmoke", icon: "textures/emotes/sitsmoke" },
      { label: "Smoke", anim: "smoke", icon: "textures/emotes/smoke" },
      { label: "Summon", anim: "summon", icon: "textures/emotes/summon" },
      { label: "Sitinbeach.2", anim: "sitinbeach.2", icon: "textures/emotes/sitinbeach.2" },
      { label: "Leantree", anim: "leantree", icon: "textures/emotes/leantree" },
      { label: "Leantree.2", anim: "leantree.2", icon: "textures/emotes/leantree.2" },
      { label: "Snow", anim: "snow", icon: "textures/emotes/snow" },
      { label: "Sit333", anim: "sit333", icon: "textures/emotes/sit333" },
      { label: "Sleep3", anim: "sleep3", icon: "textures/emotes/sleep3" },
      { label: "Sit555", anim: "sit555", icon: "textures/emotes/sit555" },
      { label: "Coverface", anim: "coverface", icon: "textures/emotes/coverface" },
      { label: "Tposess", anim: "tposess", icon: "textures/emotes/tposess" },
      { label: "Hskt1", anim: "hskt1", icon: "textures/emotes/hskt1" },
      { label: "Napwyou.2", anim: "napwyou.2", icon: "textures/emotes/napwyou.2" },
      { label: "Meme1", anim: "meme1", icon: "textures/emotes/meme1" },
      { label: "Napwyou", anim: "napwyou", icon: "textures/emotes/napwyou" },
      { label: "Hskt2", anim: "hskt2", icon: "textures/emotes/hskt2" },
      { label: "Sword1", anim: "sword1", icon: "textures/emotes/sword1" },
      { label: "Small", anim: "small", icon: "textures/emotes/small" },
      { label: "Gojo", anim: "gojo", icon: "textures/emotes/gojo" },
      { label: "Chill", anim: "chill", icon: "textures/emotes/chill" },
      { label: "Sitwyou2", anim: "sitwyou2", icon: "textures/emotes/sitwyou2" },
      { label: "Sitwyou", anim: "sitwyou", icon: "textures/emotes/sitwyou" },
      { label: "Relaxsleep", anim: "relaxsleep", icon: "textures/emotes/relaxsleep" },
    ],
  },
  {
    id: "special",
    type: "CATEGORY",
    label: "Emote Special",
    title: "Special Emotes",
    icon: "textures/emotes/icon_special",
    data: [
      { label: "Twerking", anim: "perreo", icon: "textures/emotes/perreo" },
      { label: "Helicopter", anim: "helicopter", icon: "textures/emotes/helicopter" },
      { label: "Take the T", anim: "baile_25", icon: "textures/emotes/baile_25" },
      { label: "Take the L", anim: "baile_18", icon: "textures/emotes/baile_18" },
      { label: "Llorar", anim: "llorar", icon: "textures/emotes/llorar" },
      { label: "Aquiestoy", anim: "aquiestoy", icon: "textures/emotes/aquiestoy" },
      { label: "Arigato", anim: "arigato", icon: "textures/emotes/arigato" },
      { label: "Floss", anim: "baile", icon: "textures/emotes/baile" },
      { label: "Desperate", anim: "baile_21", icon: "textures/emotes/baile_21" },
      { label: "Best Mates", anim: "baile_19", icon: "textures/emotes/baile_19" },
      { label: "Dab", anim: "dab", icon: "textures/emotes/dab" },
      { label: "Flip", anim: "flip_atras", icon: "textures/emotes/flip_atras" },
      { label: "Naca", anim: "naca", icon: "textures/emotes/naca" },
      { label: "Risa", anim: "risa", icon: "textures/emotes/risa" },
      { label: "T Pose", anim: "t-pose", icon: "textures/emotes/t-pose" },
      { label: "Zero Two", anim: "sneaking_1", icon: "textures/emotes/sneaking_1" },
    ],
  },
  {
    id: "general",
    type: "CATEGORY",
    label: "Emote General",
    title: "General Emotes",
    icon: "textures/emotes/icon_normal",
    data: [
      { label: "Point Right", anim: "so14", icon: "textures/emotes/so14" },
      { label: "No Way", anim: "so15", icon: "textures/emotes/so15" },
      { label: "Chill", anim: "so13", icon: "textures/emotes/so13" },
      { label: "Shy", anim: "so8", icon: "textures/emotes/so8" },
      { label: "Act Cool", anim: "so1", icon: "textures/emotes/so1" },
      { label: "Sit Chill", anim: "so3", icon: "textures/emotes/so3" },
      { label: "Spin", anim: "so5", icon: "textures/emotes/so5" },
      { label: "Are you here?", anim: "so7", icon: "textures/emotes/so7" },
      { label: "Im here", anim: "so9", icon: "textures/emotes/so9" },
      { label: "Point Up", anim: "so10", icon: "textures/emotes/so10" },
      { label: "Sit Sad", anim: "so11", icon: "textures/emotes/so11" },
      { label: "Nap", anim: "so17", icon: "textures/emotes/so17" },
      { label: "Leg Pain", anim: "so18", icon: "textures/emotes/so18" },
      { label: "Sit Play", anim: "so19", icon: "textures/emotes/so19" },
      { label: "Moon Walk", anim: "so16", icon: "textures/emotes/so16" },
      { label: "Size Large", anim: "big", icon: "textures/emotes/so2" },
      { label: "Size Small", anim: "so4", icon: "textures/emotes/so4" },
      { label: "Size Tiny", anim: "so6", icon: "textures/emotes/so6" },
    ],
  },
  {
    id: "post",
    type: "CATEGORY",
    label: "Emote Post",
    title: "Post Emotes",
    icon: "textures/emotes/icon_post",
    data: [
      { label: "Point Left", anim: "play8", icon: "textures/emotes/play8" },
      { label: "Fight Stance", anim: "play10", icon: "textures/emotes/play10" },
      { label: "Polite", anim: "play13", icon: "textures/emotes/play13" },
      { label: "Begging", anim: "play12", icon: "textures/emotes/play12" },
      { label: "Lay Flat", anim: "play11", icon: "textures/emotes/play11" },
      { label: "Sit Play", anim: "play17", icon: "textures/emotes/play17" },
      { label: "Sit Rest", anim: "play2", icon: "textures/emotes/play2" },
      { label: "Sit Act Left", anim: "play19", icon: "textures/emotes/play19" },
      { label: "Fold Legs", anim: "play4", icon: "textures/emotes/play4" },
      { label: "Sit Act Right", anim: "play5", icon: "textures/emotes/play5" },
      { label: "Hold Left Hand", anim: "play6", icon: "textures/emotes/play6" },
      { label: "Hold Right Hand", anim: "play7", icon: "textures/emotes/play7" },
      { label: "Lean", anim: "play1", icon: "textures/emotes/play1" },
      { label: "Tilt", anim: "play9", icon: "textures/emotes/play9" },
      { label: "Stand Act", anim: "play3", icon: "textures/emotes/play3" },
      { label: "Lay Chill", anim: "play14", icon: "textures/emotes/play14" },
      { label: "Leaning", anim: "play15", icon: "textures/emotes/play15" },
      { label: "Why?", anim: "play16", icon: "textures/emotes/play16" },
      { label: "Lean Chair", anim: "play18", icon: "textures/emotes/play18" },
    ],
  },
  {
    id: "stop",
    type: "ACTION",
    label: "[STOP]",
    title: null,
    icon: "textures/emotes/ClearC",
    data: CONFIG.STOP_COMMAND,
  },
];
